remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: MSc Artificial Intelligence ePortfolio
description: Course Artefacts and Reflections
math: true

# this is a way to inject the repo branch we build this site from
github_branch: main